# Generated by Django 3.0.4 on 2021-04-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210423_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
