# Generated by Django 3.0.4 on 2021-05-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210423_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False, 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'managed': False, 'verbose_name': 'Способ доставки', 'verbose_name_plural': 'Способы доставки'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False, 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'managed': False, 'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'managed': False, 'verbose_name': 'Статус закза', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'managed': False, 'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={'managed': False, 'verbose_name': 'Платформа', 'verbose_name_plural': 'Платформы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
